server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${HOST:localhost}:${PORT:5432}/${DB_NAME:coffee_house_orders}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
